Exercise 2: Count decile
nikol1655/myRepository pull request #1
Opened 2023-03-02 11:59 UTC by nikol1655

2023-03-03 20:07 UTC, jaroslawwoloch requested changes

2023-03-03 20:07 UTC, jaroslawwoloch commented on src/Main.java
> +            number = scanner.nextLong();
nextInt is enough.

2023-03-03 20:07 UTC, jaroslawwoloch commented on src/Main.java
> +    private static long countDecile(List<Long> numbers, double decile) {
why static

2023-03-03 20:07 UTC, jaroslawwoloch commented on src/Main.java
> +    private static List<Long> getSortedListFromUser(long number, String userAnswer) {
why static

2023-03-06 08:28 UTC, nikol1655 commented on src/Main.java
> +    private static List<Long> getSortedListFromUser(long number, String userAnswer) {
I cannot call the method  _getSortedListFromUser_ when I delete static: "Non-static method 'countDecile(java.util.List<java.lang.Long>, double)' cannot be referenced from a static context"

2023-03-06 08:28 UTC, nikol1655 commented on src/Main.java
> +    private static long countDecile(List<Long> numbers, double decile) {
I cannot call the method _countDecile_  when I delete static: "Non-static method 'countDecile(java.util.List<java.lang.Long>, double)' cannot be referenced from a static context"

2023-04-04 07:16 UTC, merged